name: TEMPLATESCI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run assets and pytest tests
        run: |
          docker pull blsq/openhexa-blsq-environment:latest
          ./scripts/tests.sh