name: TEMPLATESCI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run assets and pytest tests
        run: |
          docker pull blsq/openhexa-blsq-environment:latest
          ./scripts/tests.sh


      - name: List coverage files
        run: |
          echo "Checking if coverage files exist..."
          ls
          echo "end of ls"
          pwd
          echo "end of pwd"
          ls -l pytest-coverage.txt pytest.xml || echo "⚠️ Files not found"

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ../pytest-coverage.txt
          junitxml-path: ../pytest.xml