name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: blsq/openhexa-blsq-environment:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run assets
        run: ./scripts/tests.sh

      - name: Run pytest with coverage
        run: |
          pytest --cov=. --cov-report=term
