name: Push dhis2_to_dhis2_data_elements

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push_dhis2_to_dhis2_data_elements.yaml"
      - "dhis2_to_dhis2_data_elements/**"
      - "!dhis2_to_dhis2_data_elements/docs/**"
      - "!dhis2_to_dhis2_data_elements/README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "ds-templates"
          token: ${{ secrets.OH_TOKEN }}

      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push dhis2_to_dhis2_data_elements \
            --code "dhis2-to-dhis2-data-elements" \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/BLSQ/openhexa-templates-ds/commit/${{ github.sha }}" \
            --yes