name: Push dhis2_metadata_extract

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push_dhis2_metadata_extract.yaml"
      - "dhis2_metadata_extract/**"
      - "!dhis2_metadata_extract/docs/**"
      - "!dhis2_metadata_extract/README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "ds-templates"
          token: ${{ secrets.OH_TOKEN }}

      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push dhis2_metadata_extract \
            --code "dhis2-metadata-extract" \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/BLSQ/openhexa-templates-ds/commit/${{ github.sha }}" \
            --yes
