name: Push era5_aggregate pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push_era5_aggregate.yaml"
      - "era5_aggregate/**"
      - "!era5_aggregate/docs/**"
      - "!era5_aggregate/README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "ds-templates"
          token: ${{ secrets.OH_TOKEN }}

      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push era5_aggregate \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/BLSQ/openhexa-templates-ds/commit/${{ github.sha }}" \
            --yes
