name: Push era5_sync pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push_era5_sync.yaml"
      - "era5_sync/**"
      - "!era5_sync/docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: 'ds-templates'
          token: ${{ secrets.OH_TOKEN }}
          openhexa_version: '2.1.2'

      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push era5_sync \
            --code "era5-sync" \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/BLSQ/openhexa-templates-ds/commit/${{ github.sha }}" \
            --yes
