name: Push dhis2_extract_events pipeline

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dhis2_extract_events.yaml"
      - "dhis2_extract_events/**"
      - "!dhis2_extract_events/docs/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: 'ds-templates'
          token: ${{ secrets.OH_TOKEN }}
          openhexa_version: '2.1.2'

      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push dhis2_extract_events \
            --code "dhis2-extract-events" \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/BLSQ/openhexa-templates-ds/commit/${{ github.sha }}" \
            --yes
