name: OPENHEXA TEMPLATES TESTS

on:
  push:
    paths:
      - ".github/workflows/pytest.yml"
      - "*/pipeline.py"
  pull_request:
    paths:
      - ".github/workflows/pytest.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace:  "ds-templates"
          token: ${{ secrets.OH_TOKEN }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov

      - name: Run tests with pytest
        run: |
          pytest --maxfail=3 --disable-warnings -q --cov=openhexa_templates_ds --cov-report=xml
